# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loadlogdata.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoadLogData(object):
    def setupUi(self, LoadLogData):
        LoadLogData.setObjectName("LoadLogData")
        LoadLogData.resize(1301, 550)
        LoadLogData.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget = QtWidgets.QWidget(LoadLogData)
        self.widget.setGeometry(QtCore.QRect(20, 20, 1261, 511))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_7 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_7.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableView_2 = QtWidgets.QTableView(self.groupBox_7)
        self.tableView_2.setObjectName("tableView_2")
        self.horizontalLayout_2.addWidget(self.tableView_2)
        self.horizontalLayout.addWidget(self.groupBox_7)
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setStyleSheet("\n"
"background-color: rgb(166, 166, 166);")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 30, 201, 111))
        self.groupBox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.sb_ac_max = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.sb_ac_max.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_ac_max.setSuffix("")
        self.sb_ac_max.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.sb_ac_max.setObjectName("sb_ac_max")
        self.gridLayout.addWidget(self.sb_ac_max, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.sb_ac_min = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.sb_ac_min.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_ac_min.setSuffix("")
        self.sb_ac_min.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.sb_ac_min.setObjectName("sb_ac_min")
        self.gridLayout.addWidget(self.sb_ac_min, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.sb_ac_cor = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.sb_ac_cor.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_ac_cor.setSuffix("")
        self.sb_ac_cor.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.sb_ac_cor.setObjectName("sb_ac_cor")
        self.gridLayout.addWidget(self.sb_ac_cor, 2, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(210, 30, 191, 111))
        self.groupBox_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.sb_den_max = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.sb_den_max.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_den_max.setSuffix("")
        self.sb_den_max.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.sb_den_max.setObjectName("sb_den_max")
        self.gridLayout_2.addWidget(self.sb_den_max, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.sb_den_min = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.sb_den_min.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_den_min.setSuffix("")
        self.sb_den_min.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.sb_den_min.setObjectName("sb_den_min")
        self.gridLayout_2.addWidget(self.sb_den_min, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.sb_den_cor = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.sb_den_cor.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_den_cor.setSuffix("")
        self.sb_den_cor.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.sb_den_cor.setObjectName("sb_den_cor")
        self.gridLayout_2.addWidget(self.sb_den_cor, 2, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 160, 201, 121))
        self.groupBox_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 0, 1, 1)
        self.sb_cal_max = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.sb_cal_max.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_cal_max.setSuffix("")
        self.sb_cal_max.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.sb_cal_max.setObjectName("sb_cal_max")
        self.gridLayout_3.addWidget(self.sb_cal_max, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.sb_cal_cor = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.sb_cal_cor.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_cal_cor.setSuffix("")
        self.sb_cal_cor.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.sb_cal_cor.setObjectName("sb_cal_cor")
        self.gridLayout_3.addWidget(self.sb_cal_cor, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.sb_cal_min = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.sb_cal_min.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_cal_min.setSuffix("")
        self.sb_cal_min.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.sb_cal_min.setObjectName("sb_cal_min")
        self.gridLayout_3.addWidget(self.sb_cal_min, 1, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(210, 160, 191, 121))
        self.groupBox_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.groupBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_19 = QtWidgets.QLabel(self.groupBox_5)
        self.label_19.setObjectName("label_19")
        self.gridLayout_7.addWidget(self.label_19, 2, 0, 1, 1)
        self.sb_gr_max = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.sb_gr_max.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_gr_max.setSuffix("")
        self.sb_gr_max.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.sb_gr_max.setObjectName("sb_gr_max")
        self.gridLayout_7.addWidget(self.sb_gr_max, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_5)
        self.label_20.setObjectName("label_20")
        self.gridLayout_7.addWidget(self.label_20, 1, 0, 1, 1)
        self.sb_gr_cor = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.sb_gr_cor.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_gr_cor.setSuffix("")
        self.sb_gr_cor.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.sb_gr_cor.setObjectName("sb_gr_cor")
        self.gridLayout_7.addWidget(self.sb_gr_cor, 2, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_5)
        self.label_21.setObjectName("label_21")
        self.gridLayout_7.addWidget(self.label_21, 0, 0, 1, 1)
        self.sb_gr_min = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.sb_gr_min.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_gr_min.setSuffix("")
        self.sb_gr_min.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.sb_gr_min.setObjectName("sb_gr_min")
        self.gridLayout_7.addWidget(self.sb_gr_min, 1, 1, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 310, 200, 121))
        self.groupBox_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.groupBox_9.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_22 = QtWidgets.QLabel(self.groupBox_9)
        self.label_22.setObjectName("label_22")
        self.gridLayout_8.addWidget(self.label_22, 2, 0, 1, 1)
        self.sb_sp_max = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.sb_sp_max.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_sp_max.setSuffix("")
        self.sb_sp_max.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.sb_sp_max.setObjectName("sb_sp_max")
        self.gridLayout_8.addWidget(self.sb_sp_max, 0, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_9)
        self.label_23.setObjectName("label_23")
        self.gridLayout_8.addWidget(self.label_23, 1, 0, 1, 1)
        self.sb_sp_cor = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.sb_sp_cor.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_sp_cor.setSuffix("")
        self.sb_sp_cor.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.sb_sp_cor.setObjectName("sb_sp_cor")
        self.gridLayout_8.addWidget(self.sb_sp_cor, 2, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_9)
        self.label_24.setObjectName("label_24")
        self.gridLayout_8.addWidget(self.label_24, 0, 0, 1, 1)
        self.sb_sp_min = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.sb_sp_min.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_sp_min.setSuffix("")
        self.sb_sp_min.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.sb_sp_min.setObjectName("sb_sp_min")
        self.gridLayout_8.addWidget(self.sb_sp_min, 1, 1, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(220, 340, 181, 71))
        self.widget1.setObjectName("widget1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pb_handle = QtWidgets.QPushButton(self.widget1)
        self.pb_handle.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pb_handle.setObjectName("pb_handle")
        self.gridLayout_4.addWidget(self.pb_handle, 1, 0, 1, 1)
        self.pb_load = QtWidgets.QPushButton(self.widget1)
        self.pb_load.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pb_load.setObjectName("pb_load")
        self.gridLayout_4.addWidget(self.pb_load, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_8 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_8.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableView_3 = QtWidgets.QTableView(self.groupBox_8)
        self.tableView_3.setObjectName("tableView_3")
        self.horizontalLayout_3.addWidget(self.tableView_3)
        self.horizontalLayout.addWidget(self.groupBox_8)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)

        self.retranslateUi(LoadLogData)
        QtCore.QMetaObject.connectSlotsByName(LoadLogData)

    def retranslateUi(self, LoadLogData):
        _translate = QtCore.QCoreApplication.translate
        LoadLogData.setWindowTitle(_translate("LoadLogData", "导入测井文件"))
        self.groupBox_7.setTitle(_translate("LoadLogData", "初始测井数据"))
        self.groupBox.setTitle(_translate("LoadLogData", "数据预处理："))
        self.groupBox_2.setTitle(_translate("LoadLogData", "声波时差处理："))
        self.label.setText(_translate("LoadLogData", "Max(μs/m)"))
        self.label_2.setText(_translate("LoadLogData", "Min(μs/m)"))
        self.label_3.setText(_translate("LoadLogData", "校正值"))
        self.groupBox_3.setTitle(_translate("LoadLogData", "密度处理："))
        self.label_4.setText(_translate("LoadLogData", "Max(g/cm*3)"))
        self.label_5.setText(_translate("LoadLogData", "Min(g/cm*3)"))
        self.label_6.setText(_translate("LoadLogData", "校正值"))
        self.groupBox_4.setTitle(_translate("LoadLogData", "井径处理："))
        self.label_9.setText(_translate("LoadLogData", "校正值"))
        self.label_8.setText(_translate("LoadLogData", "Min(cm)"))
        self.label_7.setText(_translate("LoadLogData", "Max(cm)"))
        self.groupBox_5.setTitle(_translate("LoadLogData", "自然伽马处理："))
        self.label_19.setText(_translate("LoadLogData", "校正值"))
        self.label_20.setText(_translate("LoadLogData", "Min(API)"))
        self.label_21.setText(_translate("LoadLogData", "Max(API)"))
        self.groupBox_9.setTitle(_translate("LoadLogData", "自然电位处理："))
        self.label_22.setText(_translate("LoadLogData", "校正值"))
        self.label_23.setText(_translate("LoadLogData", "Min(Ω·m)"))
        self.label_24.setText(_translate("LoadLogData", "Max(Ω·m)"))
        self.pb_handle.setText(_translate("LoadLogData", "处理测井数据"))
        self.pb_load.setText(_translate("LoadLogData", "导入测井文件"))
        self.groupBox_8.setTitle(_translate("LoadLogData", "处理后的测井数据"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoadLogData = QtWidgets.QWidget()
    ui = Ui_LoadLogData()
    ui.setupUi(LoadLogData)
    LoadLogData.show()
    sys.exit(app.exec_())
