# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calproperty.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CalProperty(object):
    def setupUi(self, CalProperty):
        CalProperty.setObjectName("CalProperty")
        CalProperty.resize(1233, 726)
        self.groupBox = QtWidgets.QGroupBox(CalProperty)
        self.groupBox.setGeometry(QtCore.QRect(90, 30, 411, 291))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tv_han_data = QtWidgets.QTableView(self.groupBox)
        self.tv_han_data.setObjectName("tv_han_data")
        self.horizontalLayout.addWidget(self.tv_han_data)
        self.groupBox_2 = QtWidgets.QGroupBox(CalProperty)
        self.groupBox_2.setGeometry(QtCore.QRect(590, 30, 431, 291))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tv_result = QtWidgets.QTableView(self.groupBox_2)
        self.tv_result.setObjectName("tv_result")
        self.horizontalLayout_2.addWidget(self.tv_result)
        self.groupBox_3 = QtWidgets.QGroupBox(CalProperty)
        self.groupBox_3.setGeometry(QtCore.QRect(630, 350, 351, 251))
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_3)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 212, 152))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sb_h_xishu = QtWidgets.QDoubleSpinBox(self.layoutWidget_2)
        self.sb_h_xishu.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_h_xishu.setDecimals(3)
        self.sb_h_xishu.setProperty("value", 0.4)
        self.sb_h_xishu.setObjectName("sb_h_xishu")
        self.gridLayout_2.addWidget(self.sb_h_xishu, 1, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 1, 0, 1, 1)
        self.sb_Pp = QtWidgets.QDoubleSpinBox(self.layoutWidget_2)
        self.sb_Pp.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_Pp.setDecimals(3)
        self.sb_Pp.setProperty("value", 1.0)
        self.sb_Pp.setObjectName("sb_Pp")
        self.gridLayout_2.addWidget(self.sb_Pp, 3, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 4, 0, 1, 1)
        self.sb_Biot = QtWidgets.QDoubleSpinBox(self.layoutWidget_2)
        self.sb_Biot.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_Biot.setDecimals(3)
        self.sb_Biot.setProperty("value", 0.5)
        self.sb_Biot.setObjectName("sb_Biot")
        self.gridLayout_2.addWidget(self.sb_Biot, 4, 1, 1, 1)
        self.sb_cor_density = QtWidgets.QDoubleSpinBox(self.layoutWidget_2)
        self.sb_cor_density.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_cor_density.setDecimals(3)
        self.sb_cor_density.setProperty("value", 1.0)
        self.sb_cor_density.setObjectName("sb_cor_density")
        self.gridLayout_2.addWidget(self.sb_cor_density, 2, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 3, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 0, 0, 1, 1)
        self.sb_H_xishu = QtWidgets.QDoubleSpinBox(self.layoutWidget_2)
        self.sb_H_xishu.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_H_xishu.setDecimals(3)
        self.sb_H_xishu.setProperty("value", 0.65)
        self.sb_H_xishu.setObjectName("sb_H_xishu")
        self.gridLayout_2.addWidget(self.sb_H_xishu, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(30, 20, 212, 152))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.layoutWidget_3)
        self.doubleSpinBox_4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_4.setDecimals(3)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.gridLayout_3.addWidget(self.doubleSpinBox_4, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 1, 0, 1, 1)
        self.doubleSpinBox_11 = QtWidgets.QDoubleSpinBox(self.layoutWidget_3)
        self.doubleSpinBox_11.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_11.setDecimals(3)
        self.doubleSpinBox_11.setObjectName("doubleSpinBox_11")
        self.gridLayout_3.addWidget(self.doubleSpinBox_11, 3, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 4, 0, 1, 1)
        self.doubleSpinBox_12 = QtWidgets.QDoubleSpinBox(self.layoutWidget_3)
        self.doubleSpinBox_12.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_12.setDecimals(3)
        self.doubleSpinBox_12.setObjectName("doubleSpinBox_12")
        self.gridLayout_3.addWidget(self.doubleSpinBox_12, 4, 1, 1, 1)
        self.doubleSpinBox_13 = QtWidgets.QDoubleSpinBox(self.layoutWidget_3)
        self.doubleSpinBox_13.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_13.setDecimals(3)
        self.doubleSpinBox_13.setObjectName("doubleSpinBox_13")
        self.gridLayout_3.addWidget(self.doubleSpinBox_13, 2, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 3, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 0, 0, 1, 1)
        self.doubleSpinBox_14 = QtWidgets.QDoubleSpinBox(self.layoutWidget_3)
        self.doubleSpinBox_14.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_14.setDecimals(3)
        self.doubleSpinBox_14.setObjectName("doubleSpinBox_14")
        self.gridLayout_3.addWidget(self.doubleSpinBox_14, 0, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_3.addWidget(self.tabWidget)
        self.groupBox_4 = QtWidgets.QGroupBox(CalProperty)
        self.groupBox_4.setGeometry(QtCore.QRect(150, 370, 211, 141))
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.sb_k_ymod = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.sb_k_ymod.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_k_ymod.setDecimals(3)
        self.sb_k_ymod.setMinimum(-99.0)
        self.sb_k_ymod.setObjectName("sb_k_ymod")
        self.horizontalLayout_4.addWidget(self.sb_k_ymod)
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.sb_b_ymod = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.sb_b_ymod.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_b_ymod.setDecimals(3)
        self.sb_b_ymod.setMinimum(-99.0)
        self.sb_b_ymod.setObjectName("sb_b_ymod")
        self.horizontalLayout_4.addWidget(self.sb_b_ymod)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.sb_k_pois = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.sb_k_pois.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_k_pois.setDecimals(3)
        self.sb_k_pois.setMinimum(-99.0)
        self.sb_k_pois.setObjectName("sb_k_pois")
        self.horizontalLayout_5.addWidget(self.sb_k_pois)
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.sb_b_pois = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.sb_b_pois.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_b_pois.setDecimals(3)
        self.sb_b_pois.setMinimum(-99.0)
        self.sb_b_pois.setObjectName("sb_b_pois")
        self.horizontalLayout_5.addWidget(self.sb_b_pois)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.pb_convert = QtWidgets.QPushButton(CalProperty)
        self.pb_convert.setGeometry(QtCore.QRect(550, 620, 91, 31))
        self.pb_convert.setObjectName("pb_convert")

        self.retranslateUi(CalProperty)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CalProperty)

    def retranslateUi(self, CalProperty):
        _translate = QtCore.QCoreApplication.translate
        CalProperty.setWindowTitle(_translate("CalProperty", "岩石参数计算"))
        self.groupBox.setTitle(_translate("CalProperty", "处理后的测井数据："))
        self.groupBox_2.setTitle(_translate("CalProperty", "岩石参数计算结果："))
        self.groupBox_3.setTitle(_translate("CalProperty", "水平地应力计算公式选择："))
        self.label_15.setText(_translate("CalProperty", "水平最小地应力(ζh)系数"))
        self.label_18.setText(_translate("CalProperty", "Biot系数（α）"))
        self.label_20.setText(_translate("CalProperty", "地层孔隙压力系数（Pp）"))
        self.label_21.setText(_translate("CalProperty", "水平最大地应力(ζH)系数"))
        self.label_22.setText(_translate("CalProperty", "测井段以上岩石密度（g/cm3)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("CalProperty", "各向同性模型"))
        self.label_16.setText(_translate("CalProperty", "水平最大地应力(ζh)系数"))
        self.label_19.setText(_translate("CalProperty", "Biot系数（α）"))
        self.label_23.setText(_translate("CalProperty", "地层孔隙压力系数"))
        self.label_24.setText(_translate("CalProperty", "水平最大地应力(ζH)系数"))
        self.label_25.setText(_translate("CalProperty", "非测井段岩石密度（g/cm3)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("CalProperty", "横向各向同性模型"))
        self.groupBox_4.setTitle(_translate("CalProperty", "模量转换参数："))
        self.label_9.setText(_translate("CalProperty", "动静态杨氏模量转换"))
        self.label.setText(_translate("CalProperty", "Es"))
        self.label_2.setText(_translate("CalProperty", "="))
        self.label_11.setText(_translate("CalProperty", "*"))
        self.label_4.setText(_translate("CalProperty", "Ed"))
        self.label_3.setText(_translate("CalProperty", "+"))
        self.label_10.setText(_translate("CalProperty", "动静态泊松比转换"))
        self.label_5.setText(_translate("CalProperty", "μs"))
        self.label_6.setText(_translate("CalProperty", "="))
        self.label_12.setText(_translate("CalProperty", "*"))
        self.label_7.setText(_translate("CalProperty", "μd"))
        self.label_8.setText(_translate("CalProperty", "+"))
        self.pb_convert.setText(_translate("CalProperty", "数据转换"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CalProperty = QtWidgets.QWidget()
    ui = Ui_CalProperty()
    ui.setupUi(CalProperty)
    CalProperty.show()
    sys.exit(app.exec_())
