# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calproperty.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CalProperty(object):
    def setupUi(self, CalProperty):
        CalProperty.setObjectName("CalProperty")
        CalProperty.resize(1177, 770)
        self.verticalLayout = QtWidgets.QVBoxLayout(CalProperty)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(CalProperty)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tv_han_data = QtWidgets.QTableView(self.groupBox)
        self.tv_han_data.setObjectName("tv_han_data")
        self.horizontalLayout.addWidget(self.tv_han_data)
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tv_result = QtWidgets.QTableView(self.groupBox_2)
        self.tv_result.setObjectName("tv_result")
        self.horizontalLayout_2.addWidget(self.tv_result)
        self.verticalLayout.addWidget(self.splitter)
        self.groupBox_5 = QtWidgets.QGroupBox(CalProperty)
        self.groupBox_5.setObjectName("groupBox_5")
        self.pb_convert = QtWidgets.QPushButton(self.groupBox_5)
        self.pb_convert.setGeometry(QtCore.QRect(820, 290, 141, 41))
        self.pb_convert.setObjectName("pb_convert")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 30, 211, 121))
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.sb_k_ymod = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.sb_k_ymod.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_k_ymod.setDecimals(3)
        self.sb_k_ymod.setMinimum(-99.0)
        self.sb_k_ymod.setProperty("value", 1.0)
        self.sb_k_ymod.setObjectName("sb_k_ymod")
        self.horizontalLayout_4.addWidget(self.sb_k_ymod)
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.sb_b_ymod = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.sb_b_ymod.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_b_ymod.setDecimals(3)
        self.sb_b_ymod.setMinimum(-99.0)
        self.sb_b_ymod.setObjectName("sb_b_ymod")
        self.horizontalLayout_4.addWidget(self.sb_b_ymod)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.sb_k_pois = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.sb_k_pois.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_k_pois.setDecimals(3)
        self.sb_k_pois.setMinimum(-99.0)
        self.sb_k_pois.setProperty("value", 1.0)
        self.sb_k_pois.setObjectName("sb_k_pois")
        self.horizontalLayout_5.addWidget(self.sb_k_pois)
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.sb_b_pois = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.sb_b_pois.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_b_pois.setDecimals(3)
        self.sb_b_pois.setMinimum(-99.0)
        self.sb_b_pois.setObjectName("sb_b_pois")
        self.horizontalLayout_5.addWidget(self.sb_b_pois)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 180, 212, 152))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sb_h_xishu = QtWidgets.QDoubleSpinBox(self.layoutWidget_2)
        self.sb_h_xishu.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_h_xishu.setDecimals(3)
        self.sb_h_xishu.setProperty("value", 0.4)
        self.sb_h_xishu.setObjectName("sb_h_xishu")
        self.gridLayout_2.addWidget(self.sb_h_xishu, 1, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 1, 0, 1, 1)
        self.sb_Pp = QtWidgets.QDoubleSpinBox(self.layoutWidget_2)
        self.sb_Pp.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_Pp.setDecimals(3)
        self.sb_Pp.setProperty("value", 1.0)
        self.sb_Pp.setObjectName("sb_Pp")
        self.gridLayout_2.addWidget(self.sb_Pp, 3, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 4, 0, 1, 1)
        self.sb_Biot = QtWidgets.QDoubleSpinBox(self.layoutWidget_2)
        self.sb_Biot.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_Biot.setDecimals(3)
        self.sb_Biot.setProperty("value", 1.0)
        self.sb_Biot.setObjectName("sb_Biot")
        self.gridLayout_2.addWidget(self.sb_Biot, 4, 1, 1, 1)
        self.sb_cor_density = QtWidgets.QDoubleSpinBox(self.layoutWidget_2)
        self.sb_cor_density.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_cor_density.setDecimals(3)
        self.sb_cor_density.setProperty("value", 2.0)
        self.sb_cor_density.setObjectName("sb_cor_density")
        self.gridLayout_2.addWidget(self.sb_cor_density, 2, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 3, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 0, 0, 1, 1)
        self.sb_H_xishu = QtWidgets.QDoubleSpinBox(self.layoutWidget_2)
        self.sb_H_xishu.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sb_H_xishu.setDecimals(3)
        self.sb_H_xishu.setProperty("value", 0.65)
        self.sb_H_xishu.setObjectName("sb_H_xishu")
        self.gridLayout_2.addWidget(self.sb_H_xishu, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 2, 0, 1, 1)
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget.setGeometry(QtCore.QRect(520, 180, 348, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_8.addWidget(self.label_16)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_8.addWidget(self.label_45)
        self.label_50 = QtWidgets.QLabel(self.layoutWidget)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_8.addWidget(self.label_50)
        self.k_vp90_3 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.k_vp90_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.k_vp90_3.setDecimals(3)
        self.k_vp90_3.setMinimum(-99.0)
        self.k_vp90_3.setProperty("value", 1.0)
        self.k_vp90_3.setObjectName("k_vp90_3")
        self.horizontalLayout_8.addWidget(self.k_vp90_3)
        self.label_41 = QtWidgets.QLabel(self.layoutWidget)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_8.addWidget(self.label_41)
        self.label_46 = QtWidgets.QLabel(self.layoutWidget)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_8.addWidget(self.label_46)
        self.label_51 = QtWidgets.QLabel(self.layoutWidget)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_8.addWidget(self.label_51)
        self.k_vp90_4 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.k_vp90_4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.k_vp90_4.setDecimals(3)
        self.k_vp90_4.setMinimum(-99.0)
        self.k_vp90_4.setProperty("value", 1.0)
        self.k_vp90_4.setObjectName("k_vp90_4")
        self.horizontalLayout_8.addWidget(self.k_vp90_4)
        self.label_55 = QtWidgets.QLabel(self.layoutWidget)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_8.addWidget(self.label_55)
        self.label_56 = QtWidgets.QLabel(self.layoutWidget)
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_8.addWidget(self.label_56)
        self.layoutWidget_5 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget_5.setGeometry(QtCore.QRect(520, 210, 348, 22))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_62 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_62.setObjectName("label_62")
        self.horizontalLayout_10.addWidget(self.label_62)
        self.label_63 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_63.setObjectName("label_63")
        self.horizontalLayout_10.addWidget(self.label_63)
        self.label_64 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_64.setObjectName("label_64")
        self.horizontalLayout_10.addWidget(self.label_64)
        self.k_vp90_7 = QtWidgets.QDoubleSpinBox(self.layoutWidget_5)
        self.k_vp90_7.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.k_vp90_7.setDecimals(3)
        self.k_vp90_7.setMinimum(-99.0)
        self.k_vp90_7.setProperty("value", 1.0)
        self.k_vp90_7.setObjectName("k_vp90_7")
        self.horizontalLayout_10.addWidget(self.k_vp90_7)
        self.label_65 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_65.setObjectName("label_65")
        self.horizontalLayout_10.addWidget(self.label_65)
        self.label_66 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_66.setObjectName("label_66")
        self.horizontalLayout_10.addWidget(self.label_66)
        self.label_67 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_67.setObjectName("label_67")
        self.horizontalLayout_10.addWidget(self.label_67)
        self.k_vp90_8 = QtWidgets.QDoubleSpinBox(self.layoutWidget_5)
        self.k_vp90_8.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.k_vp90_8.setDecimals(3)
        self.k_vp90_8.setMinimum(-99.0)
        self.k_vp90_8.setProperty("value", 1.0)
        self.k_vp90_8.setObjectName("k_vp90_8")
        self.horizontalLayout_10.addWidget(self.k_vp90_8)
        self.label_68 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_68.setObjectName("label_68")
        self.horizontalLayout_10.addWidget(self.label_68)
        self.label_69 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_69.setObjectName("label_69")
        self.horizontalLayout_10.addWidget(self.label_69)
        self.layoutWidget_9 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget_9.setGeometry(QtCore.QRect(520, 100, 184, 22))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_111 = QtWidgets.QLabel(self.layoutWidget_9)
        self.label_111.setObjectName("label_111")
        self.horizontalLayout_16.addWidget(self.label_111)
        self.label_112 = QtWidgets.QLabel(self.layoutWidget_9)
        self.label_112.setObjectName("label_112")
        self.horizontalLayout_16.addWidget(self.label_112)
        self.label_113 = QtWidgets.QLabel(self.layoutWidget_9)
        self.label_113.setObjectName("label_113")
        self.horizontalLayout_16.addWidget(self.label_113)
        self.label_114 = QtWidgets.QLabel(self.layoutWidget_9)
        self.label_114.setObjectName("label_114")
        self.horizontalLayout_16.addWidget(self.label_114)
        self.spinBox_3 = QtWidgets.QSpinBox(self.layoutWidget_9)
        self.spinBox_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_3.setMaximum(999999999)
        self.spinBox_3.setProperty("value", 1000000)
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout_16.addWidget(self.spinBox_3)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget1.setGeometry(QtCore.QRect(520, 150, 348, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_3.addWidget(self.label_14)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_3.addWidget(self.label_44)
        self.label_49 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_3.addWidget(self.label_49)
        self.k_vp90 = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.k_vp90.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.k_vp90.setDecimals(3)
        self.k_vp90.setMinimum(-99.0)
        self.k_vp90.setProperty("value", 1.0)
        self.k_vp90.setObjectName("k_vp90")
        self.horizontalLayout_3.addWidget(self.k_vp90)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        self.label_43 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_3.addWidget(self.label_43)
        self.label_48 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_3.addWidget(self.label_48)
        self.k_vp90_2 = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.k_vp90_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.k_vp90_2.setDecimals(3)
        self.k_vp90_2.setMinimum(-99.0)
        self.k_vp90_2.setProperty("value", 1.0)
        self.k_vp90_2.setObjectName("k_vp90_2")
        self.horizontalLayout_3.addWidget(self.k_vp90_2)
        self.label_53 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_3.addWidget(self.label_53)
        self.label_54 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_3.addWidget(self.label_54)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget2.setGeometry(QtCore.QRect(520, 70, 184, 22))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_42 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_15.addWidget(self.label_42)
        self.label_47 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_15.addWidget(self.label_47)
        self.label_52 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_15.addWidget(self.label_52)
        self.label_57 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_57.setObjectName("label_57")
        self.horizontalLayout_15.addWidget(self.label_57)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox.setMaximum(999999999)
        self.spinBox.setProperty("value", 1000000)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_15.addWidget(self.spinBox)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton.setGeometry(QtCore.QRect(320, 80, 101, 16))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_2.setGeometry(QtCore.QRect(320, 110, 121, 16))
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.groupBox_5)

        self.retranslateUi(CalProperty)
        QtCore.QMetaObject.connectSlotsByName(CalProperty)

    def retranslateUi(self, CalProperty):
        _translate = QtCore.QCoreApplication.translate
        CalProperty.setWindowTitle(_translate("CalProperty", "岩石参数计算"))
        self.groupBox.setTitle(_translate("CalProperty", "处理后的测井数据："))
        self.groupBox_2.setTitle(_translate("CalProperty", "岩石参数计算结果："))
        self.groupBox_5.setTitle(_translate("CalProperty", "地层缺省参数"))
        self.pb_convert.setText(_translate("CalProperty", "参数转换"))
        self.groupBox_4.setTitle(_translate("CalProperty", "模量转换参数："))
        self.label_9.setText(_translate("CalProperty", "动静态杨氏模量转换"))
        self.label.setText(_translate("CalProperty", "Es"))
        self.label_2.setText(_translate("CalProperty", "="))
        self.label_11.setText(_translate("CalProperty", "×"))
        self.label_4.setText(_translate("CalProperty", "Ed"))
        self.label_3.setText(_translate("CalProperty", "+"))
        self.label_10.setText(_translate("CalProperty", "动静态泊松比转换"))
        self.label_5.setText(_translate("CalProperty", "μs"))
        self.label_6.setText(_translate("CalProperty", "="))
        self.label_12.setText(_translate("CalProperty", "×"))
        self.label_7.setText(_translate("CalProperty", "μd"))
        self.label_8.setText(_translate("CalProperty", "+"))
        self.label_15.setText(_translate("CalProperty", "水平最小地应力(ζh)系数"))
        self.label_18.setText(_translate("CalProperty", "Biot系数（α）"))
        self.label_20.setText(_translate("CalProperty", "地层孔隙压力系数（Pp）"))
        self.label_21.setText(_translate("CalProperty", "水平最大地应力(ζH)系数"))
        self.label_22.setText(_translate("CalProperty", "测井段以上岩石密度（g/cm3)"))
        self.label_16.setText(_translate("CalProperty", "Vp(45°)"))
        self.label_45.setText(_translate("CalProperty", "="))
        self.label_50.setText(_translate("CalProperty", "("))
        self.label_41.setText(_translate("CalProperty", "×"))
        self.label_46.setText(_translate("CalProperty", "Vp(0°)/1000"))
        self.label_51.setText(_translate("CalProperty", "+"))
        self.label_55.setText(_translate("CalProperty", ")"))
        self.label_56.setText(_translate("CalProperty", "×1000"))
        self.label_62.setText(_translate("CalProperty", "Vs(90°)"))
        self.label_63.setText(_translate("CalProperty", "="))
        self.label_64.setText(_translate("CalProperty", "("))
        self.label_65.setText(_translate("CalProperty", "×"))
        self.label_66.setText(_translate("CalProperty", "Vs(0°)/1000"))
        self.label_67.setText(_translate("CalProperty", "+"))
        self.label_68.setText(_translate("CalProperty", ")"))
        self.label_69.setText(_translate("CalProperty", "×1000"))
        self.label_111.setText(_translate("CalProperty", "Vs(0°)"))
        self.label_112.setText(_translate("CalProperty", "="))
        self.label_113.setText(_translate("CalProperty", "1/△ts"))
        self.label_114.setText(_translate("CalProperty", "×"))
        self.label_14.setText(_translate("CalProperty", "Vp(90°)"))
        self.label_44.setText(_translate("CalProperty", "="))
        self.label_49.setText(_translate("CalProperty", "("))
        self.label_13.setText(_translate("CalProperty", "×"))
        self.label_43.setText(_translate("CalProperty", "Vp(0°)/1000"))
        self.label_48.setText(_translate("CalProperty", "+"))
        self.label_53.setText(_translate("CalProperty", ")"))
        self.label_54.setText(_translate("CalProperty", "×1000"))
        self.label_42.setText(_translate("CalProperty", "Vp(0°)"))
        self.label_47.setText(_translate("CalProperty", "="))
        self.label_52.setText(_translate("CalProperty", "1/△tp"))
        self.label_57.setText(_translate("CalProperty", "×"))
        self.radioButton.setText(_translate("CalProperty", "各向同性模型"))
        self.radioButton_2.setText(_translate("CalProperty", "横向各向同性模型"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CalProperty = QtWidgets.QWidget()
    ui = Ui_CalProperty()
    ui.setupUi(CalProperty)
    CalProperty.show()
    sys.exit(app.exec_())
