# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(924, 570)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        Form.setFont(font)
        Form.setAutoFillBackground(False)
        self.formGroupBox = QtWidgets.QGroupBox(Form)
        self.formGroupBox.setGeometry(QtCore.QRect(10, 20, 181, 251))
        self.formGroupBox.setFlat(False)
        self.formGroupBox.setObjectName("formGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.formGroupBox)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.lb_permeability = QtWidgets.QLabel(self.formGroupBox)
        self.lb_permeability.setObjectName("lb_permeability")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lb_permeability)
        self.lb_permeability_submit = QtWidgets.QToolButton(self.formGroupBox)
        self.lb_permeability_submit.setObjectName("lb_permeability_submit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lb_permeability_submit)
        self.lb_porosity = QtWidgets.QLabel(self.formGroupBox)
        self.lb_porosity.setObjectName("lb_porosity")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lb_porosity)
        self.lb_porosity_submit = QtWidgets.QToolButton(self.formGroupBox)
        self.lb_porosity_submit.setObjectName("lb_porosity_submit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lb_porosity_submit)
        self.lb_youngs_module = QtWidgets.QLabel(self.formGroupBox)
        self.lb_youngs_module.setObjectName("lb_youngs_module")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lb_youngs_module)
        self.lb_youngs_module_submit = QtWidgets.QToolButton(self.formGroupBox)
        self.lb_youngs_module_submit.setObjectName("lb_youngs_module_submit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lb_youngs_module_submit)
        self.lb_poison_ratio = QtWidgets.QLabel(self.formGroupBox)
        self.lb_poison_ratio.setObjectName("lb_poison_ratio")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lb_poison_ratio)
        self.lb_poison_ratio_submit = QtWidgets.QToolButton(self.formGroupBox)
        self.lb_poison_ratio_submit.setObjectName("lb_poison_ratio_submit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lb_poison_ratio_submit)
        self.lb_v_stress = QtWidgets.QLabel(self.formGroupBox)
        self.lb_v_stress.setObjectName("lb_v_stress")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lb_v_stress)
        self.lb_v_stress_submit = QtWidgets.QToolButton(self.formGroupBox)
        self.lb_v_stress_submit.setObjectName("lb_v_stress_submit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lb_v_stress_submit)
        self.lb_h_stress = QtWidgets.QLabel(self.formGroupBox)
        self.lb_h_stress.setObjectName("lb_h_stress")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lb_h_stress)
        self.lb_h_stress_submit = QtWidgets.QToolButton(self.formGroupBox)
        self.lb_h_stress_submit.setObjectName("lb_h_stress_submit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lb_h_stress_submit)
        self.lb_frac_toughness = QtWidgets.QLabel(self.formGroupBox)
        self.lb_frac_toughness.setObjectName("lb_frac_toughness")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lb_frac_toughness)
        self.lb_frac_toughness_submit = QtWidgets.QToolButton(self.formGroupBox)
        self.lb_frac_toughness_submit.setObjectName("lb_frac_toughness_submit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lb_frac_toughness_submit)
        self.lb_natural_frac = QtWidgets.QLabel(self.formGroupBox)
        self.lb_natural_frac.setObjectName("lb_natural_frac")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lb_natural_frac)
        self.lb_natural_frac_submit = QtWidgets.QToolButton(self.formGroupBox)
        self.lb_natural_frac_submit.setObjectName("lb_natural_frac_submit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lb_natural_frac_submit)
        self.verticalGroupBox = QtWidgets.QGroupBox(Form)
        self.verticalGroupBox.setGeometry(QtCore.QRect(200, 10, 700, 300))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.verticalGroupBox.setFont(font)
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_graph = QtWidgets.QVBoxLayout()
        self.verticalLayout_graph.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_graph.setObjectName("verticalLayout_graph")
        self.verticalLayout.addLayout(self.verticalLayout_graph)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(200, 350, 781, 201))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(90, 20, 231, 181))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 197, 151))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 2, 1, 1)
        self.le_show_lv3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.le_show_lv3.sizePolicy().hasHeightForWidth())
        self.le_show_lv3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.le_show_lv3.setFont(font)
        self.le_show_lv3.setText("")
        self.le_show_lv3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_show_lv3.setReadOnly(True)
        self.le_show_lv3.setObjectName("le_show_lv3")
        self.gridLayout_2.addWidget(self.le_show_lv3, 2, 1, 1, 1)
        self.le_show_lv2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.le_show_lv2.sizePolicy().hasHeightForWidth())
        self.le_show_lv2.setSizePolicy(sizePolicy)
        self.le_show_lv2.setText("")
        self.le_show_lv2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_show_lv2.setReadOnly(True)
        self.le_show_lv2.setObjectName("le_show_lv2")
        self.gridLayout_2.addWidget(self.le_show_lv2, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.le_show_lv1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.le_show_lv1.sizePolicy().hasHeightForWidth())
        self.le_show_lv1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.le_show_lv1.setFont(font)
        self.le_show_lv1.setText("")
        self.le_show_lv1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_show_lv1.setReadOnly(True)
        self.le_show_lv1.setObjectName("le_show_lv1")
        self.gridLayout_2.addWidget(self.le_show_lv1, 0, 1, 1, 1)
        self.le_show_lv4 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.le_show_lv4.sizePolicy().hasHeightForWidth())
        self.le_show_lv4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.le_show_lv4.setFont(font)
        self.le_show_lv4.setText("")
        self.le_show_lv4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_show_lv4.setReadOnly(True)
        self.le_show_lv4.setObjectName("le_show_lv4")
        self.gridLayout_2.addWidget(self.le_show_lv4, 3, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 3, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 3, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 4, 0, 1, 1)
        self.le_show_lv5 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.le_show_lv5.sizePolicy().hasHeightForWidth())
        self.le_show_lv5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.le_show_lv5.setFont(font)
        self.le_show_lv5.setText("")
        self.le_show_lv5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_show_lv5.setReadOnly(True)
        self.le_show_lv5.setObjectName("le_show_lv5")
        self.gridLayout_2.addWidget(self.le_show_lv5, 4, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 4, 2, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_5.setGeometry(QtCore.QRect(400, 20, 281, 181))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_5)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 30, 255, 141))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 1, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 2, 0, 1, 3)
        self.le_show_startdessert = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.le_show_startdessert.sizePolicy().hasHeightForWidth())
        self.le_show_startdessert.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.le_show_startdessert.setFont(font)
        self.le_show_startdessert.setText("")
        self.le_show_startdessert.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_show_startdessert.setReadOnly(True)
        self.le_show_startdessert.setObjectName("le_show_startdessert")
        self.gridLayout_3.addWidget(self.le_show_startdessert, 0, 1, 1, 1)
        self.le_show_enddessert = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.le_show_enddessert.sizePolicy().hasHeightForWidth())
        self.le_show_enddessert.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.le_show_enddessert.setFont(font)
        self.le_show_enddessert.setText("")
        self.le_show_enddessert.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_show_enddessert.setReadOnly(True)
        self.le_show_enddessert.setObjectName("le_show_enddessert")
        self.gridLayout_3.addWidget(self.le_show_enddessert, 1, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 0, 2, 1, 1)
        self.pb_show_part_2 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pb_show_part_2.setObjectName("pb_show_part_2")
        self.gridLayout_3.addWidget(self.pb_show_part_2, 3, 0, 1, 2)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(210, 310, 731, 41))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(300, 10, 221, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lb_depth = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_depth.sizePolicy().hasHeightForWidth())
        self.lb_depth.setSizePolicy(sizePolicy)
        self.lb_depth.setObjectName("lb_depth")
        self.horizontalLayout.addWidget(self.lb_depth)
        self.le_startdepth = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_startdepth.sizePolicy().hasHeightForWidth())
        self.le_startdepth.setSizePolicy(sizePolicy)
        self.le_startdepth.setSizeIncrement(QtCore.QSize(0, 0))
        self.le_startdepth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_startdepth.setObjectName("le_startdepth")
        self.horizontalLayout.addWidget(self.le_startdepth)
        self.lb_maohao = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_maohao.sizePolicy().hasHeightForWidth())
        self.lb_maohao.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lb_maohao.setFont(font)
        self.lb_maohao.setObjectName("lb_maohao")
        self.horizontalLayout.addWidget(self.lb_maohao)
        self.le_enddepth = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_enddepth.sizePolicy().hasHeightForWidth())
        self.le_enddepth.setSizePolicy(sizePolicy)
        self.le_enddepth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_enddepth.setObjectName("le_enddepth")
        self.horizontalLayout.addWidget(self.le_enddepth)
        self.pb_show_part = QtWidgets.QPushButton(self.frame)
        self.pb_show_part.setGeometry(QtCore.QRect(570, 10, 101, 31))
        self.pb_show_part.setObjectName("pb_show_part")
        self.compute_fi = QtWidgets.QPushButton(Form)
        self.compute_fi.setGeometry(QtCore.QRect(10, 480, 181, 61))
        self.compute_fi.setObjectName("compute_fi")
        self.verticalGroupBox.raise_()
        self.formGroupBox.raise_()
        self.groupBox_2.raise_()
        self.frame.raise_()
        self.compute_fi.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "陆相页岩可压性评价软件"))
        self.formGroupBox.setTitle(_translate("Form", "测井数据"))
        self.lb_permeability.setText(_translate("Form", "渗透率："))
        self.lb_permeability_submit.setText(_translate("Form", "上传文件"))
        self.lb_porosity.setText(_translate("Form", "孔隙度："))
        self.lb_porosity_submit.setText(_translate("Form", "上传文件"))
        self.lb_youngs_module.setText(_translate("Form", "杨氏模量："))
        self.lb_youngs_module_submit.setText(_translate("Form", "上传文件"))
        self.lb_poison_ratio.setText(_translate("Form", "泊松比："))
        self.lb_poison_ratio_submit.setText(_translate("Form", "上传文件"))
        self.lb_v_stress.setText(_translate("Form", "垂向应力："))
        self.lb_v_stress_submit.setText(_translate("Form", "上传文件"))
        self.lb_h_stress.setText(_translate("Form", "水平应力："))
        self.lb_h_stress_submit.setText(_translate("Form", "上传文件"))
        self.lb_frac_toughness.setText(_translate("Form", "断裂韧性："))
        self.lb_frac_toughness_submit.setText(_translate("Form", "上传文件"))
        self.lb_natural_frac.setText(_translate("Form", "天然裂缝："))
        self.lb_natural_frac_submit.setText(_translate("Form", "上传文件"))
        self.verticalGroupBox.setTitle(_translate("Form", "陆相页岩可压性评价剖面"))
        self.groupBox_2.setTitle(_translate("Form", "可压性评价结果"))
        self.groupBox_3.setTitle(_translate("Form", "可压性分级标准："))
        self.label_6.setText(_translate("Form", "二级："))
        self.label_9.setText(_translate("Form", "%"))
        self.label_8.setText(_translate("Form", "%"))
        self.label_11.setText(_translate("Form", "%"))
        self.label_7.setText(_translate("Form", "一级："))
        self.label_10.setText(_translate("Form", "三级："))
        self.label_13.setText(_translate("Form", "%"))
        self.label_12.setText(_translate("Form", "四级："))
        self.label_16.setText(_translate("Form", "五级："))
        self.label_18.setText(_translate("Form", "%"))
        self.groupBox_5.setTitle(_translate("Form", "可压性甜点层段"))
        self.label_19.setText(_translate("Form", "m"))
        self.label_21.setText(_translate("Form", " 最优甜点段终点深度："))
        self.label_20.setText(_translate("Form", "最优甜点段起始深度："))
        self.label_17.setText(_translate("Form", "m"))
        self.pb_show_part_2.setText(_translate("Form", "显示所有甜点层段"))
        self.lb_depth.setText(_translate("Form", "选择深度："))
        self.lb_maohao.setText(_translate("Form", ":"))
        self.pb_show_part.setText(_translate("Form", "完整可压性剖面"))
        self.compute_fi.setText(_translate("Form", "计算并绘制陆相页岩可压性剖面"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
