# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ficompute.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ficompute(object):
    def setupUi(self, ficompute):
        ficompute.setObjectName("ficompute")
        ficompute.resize(1112, 730)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ficompute.sizePolicy().hasHeightForWidth())
        ficompute.setSizePolicy(sizePolicy)
        ficompute.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(ficompute)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(11, 10, 1071, 621))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gp_param = QtWidgets.QGroupBox(self.layoutWidget)
        self.gp_param.setObjectName("gp_param")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.gp_param)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logdata = QtWidgets.QTableView(self.gp_param)
        self.logdata.setEnabled(True)
        self.logdata.setObjectName("logdata")
        self.logdata.horizontalHeader().setStretchLastSection(False)
        self.logdata.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_2.addWidget(self.logdata)
        self.verticalLayout_2.addWidget(self.gp_param)
        self.gp_weight = QtWidgets.QGroupBox(self.layoutWidget)
        self.gp_weight.setObjectName("gp_weight")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gp_weight)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lb_fi = QtWidgets.QLabel(self.gp_weight)
        self.lb_fi.setMinimumSize(QtCore.QSize(0, 30))
        self.lb_fi.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lb_fi.setObjectName("lb_fi")
        self.horizontalLayout.addWidget(self.lb_fi)
        self.lb_equal = QtWidgets.QLabel(self.gp_weight)
        self.lb_equal.setMinimumSize(QtCore.QSize(0, 30))
        self.lb_equal.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lb_equal.setObjectName("lb_equal")
        self.horizontalLayout.addWidget(self.lb_equal)
        self.f1 = QtWidgets.QDoubleSpinBox(self.gp_weight)
        self.f1.setEnabled(False)
        self.f1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.f1.setMaximum(1.0)
        self.f1.setProperty("value", 0.2)
        self.f1.setObjectName("f1")
        self.horizontalLayout.addWidget(self.f1)
        self.lb_f1 = QtWidgets.QLabel(self.gp_weight)
        self.lb_f1.setMinimumSize(QtCore.QSize(0, 30))
        self.lb_f1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lb_f1.setObjectName("lb_f1")
        self.horizontalLayout.addWidget(self.lb_f1)
        self.lb_plus1 = QtWidgets.QLabel(self.gp_weight)
        self.lb_plus1.setMinimumSize(QtCore.QSize(0, 30))
        self.lb_plus1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lb_plus1.setObjectName("lb_plus1")
        self.horizontalLayout.addWidget(self.lb_plus1)
        self.f2 = QtWidgets.QDoubleSpinBox(self.gp_weight)
        self.f2.setEnabled(False)
        self.f2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.f2.setMaximum(1.0)
        self.f2.setProperty("value", 0.2)
        self.f2.setObjectName("f2")
        self.horizontalLayout.addWidget(self.f2)
        self.lb_f2 = QtWidgets.QLabel(self.gp_weight)
        self.lb_f2.setMinimumSize(QtCore.QSize(0, 30))
        self.lb_f2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lb_f2.setObjectName("lb_f2")
        self.horizontalLayout.addWidget(self.lb_f2)
        self.lb_plus2 = QtWidgets.QLabel(self.gp_weight)
        self.lb_plus2.setMinimumSize(QtCore.QSize(0, 30))
        self.lb_plus2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lb_plus2.setObjectName("lb_plus2")
        self.horizontalLayout.addWidget(self.lb_plus2)
        self.f3 = QtWidgets.QDoubleSpinBox(self.gp_weight)
        self.f3.setEnabled(False)
        self.f3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.f3.setMaximum(1.0)
        self.f3.setProperty("value", 0.2)
        self.f3.setObjectName("f3")
        self.horizontalLayout.addWidget(self.f3)
        self.lb_f3 = QtWidgets.QLabel(self.gp_weight)
        self.lb_f3.setMinimumSize(QtCore.QSize(0, 30))
        self.lb_f3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lb_f3.setObjectName("lb_f3")
        self.horizontalLayout.addWidget(self.lb_f3)
        self.lb_plus3 = QtWidgets.QLabel(self.gp_weight)
        self.lb_plus3.setMinimumSize(QtCore.QSize(0, 30))
        self.lb_plus3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lb_plus3.setObjectName("lb_plus3")
        self.horizontalLayout.addWidget(self.lb_plus3)
        self.f4 = QtWidgets.QDoubleSpinBox(self.gp_weight)
        self.f4.setEnabled(False)
        self.f4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.f4.setMaximum(1.0)
        self.f4.setProperty("value", 0.2)
        self.f4.setObjectName("f4")
        self.horizontalLayout.addWidget(self.f4)
        self.lb_f4 = QtWidgets.QLabel(self.gp_weight)
        self.lb_f4.setMinimumSize(QtCore.QSize(0, 30))
        self.lb_f4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lb_f4.setObjectName("lb_f4")
        self.horizontalLayout.addWidget(self.lb_f4)
        self.lb_plus4 = QtWidgets.QLabel(self.gp_weight)
        self.lb_plus4.setMinimumSize(QtCore.QSize(0, 30))
        self.lb_plus4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lb_plus4.setObjectName("lb_plus4")
        self.horizontalLayout.addWidget(self.lb_plus4)
        self.f5 = QtWidgets.QDoubleSpinBox(self.gp_weight)
        self.f5.setEnabled(False)
        self.f5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.f5.setMaximum(1.0)
        self.f5.setSingleStep(0.01)
        self.f5.setProperty("value", 0.2)
        self.f5.setObjectName("f5")
        self.horizontalLayout.addWidget(self.f5)
        self.lb_f5 = QtWidgets.QLabel(self.gp_weight)
        self.lb_f5.setMinimumSize(QtCore.QSize(0, 30))
        self.lb_f5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lb_f5.setObjectName("lb_f5")
        self.horizontalLayout.addWidget(self.lb_f5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pbmodify = QtWidgets.QPushButton(self.gp_weight)
        self.pbmodify.setMinimumSize(QtCore.QSize(0, 30))
        self.pbmodify.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pbmodify.setObjectName("pbmodify")
        self.horizontalLayout_3.addWidget(self.pbmodify)
        self.pbconfirm = QtWidgets.QPushButton(self.gp_weight)
        self.pbconfirm.setMinimumSize(QtCore.QSize(0, 30))
        self.pbconfirm.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pbconfirm.setObjectName("pbconfirm")
        self.horizontalLayout_3.addWidget(self.pbconfirm)
        self.pbcompute = QtWidgets.QPushButton(self.gp_weight)
        self.pbcompute.setMinimumSize(QtCore.QSize(0, 30))
        self.pbcompute.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pbcompute.setObjectName("pbcompute")
        self.horizontalLayout_3.addWidget(self.pbcompute)
        self.pbpaint = QtWidgets.QPushButton(self.gp_weight)
        self.pbpaint.setMinimumSize(QtCore.QSize(0, 30))
        self.pbpaint.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pbpaint.setObjectName("pbpaint")
        self.horizontalLayout_3.addWidget(self.pbpaint)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.textEdit = QtWidgets.QTextEdit(self.gp_weight)
        self.textEdit.setEnabled(False)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.verticalLayout_2.addWidget(self.gp_weight)
        self.verticalLayout_2.setStretch(0, 9)
        self.verticalLayout_2.setStretch(1, 2)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gp_curve = QtWidgets.QGroupBox(self.layoutWidget1)
        self.gp_curve.setMinimumSize(QtCore.QSize(400, 0))
        self.gp_curve.setObjectName("gp_curve")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.gp_curve)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.layout_curve = QtWidgets.QVBoxLayout()
        self.layout_curve.setObjectName("layout_curve")
        self.verticalLayout_6.addLayout(self.layout_curve)
        self.verticalLayout_3.addWidget(self.gp_curve)
        self.gp_result = QtWidgets.QGroupBox(self.layoutWidget1)
        self.gp_result.setObjectName("gp_result")
        self.layoutWidget2 = QtWidgets.QWidget(self.gp_result)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 20, 471, 201))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.le_show_lv1 = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_show_lv1.sizePolicy().hasHeightForWidth())
        self.le_show_lv1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.le_show_lv1.setFont(font)
        self.le_show_lv1.setText("")
        self.le_show_lv1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_show_lv1.setReadOnly(True)
        self.le_show_lv1.setObjectName("le_show_lv1")
        self.gridLayout.addWidget(self.le_show_lv1, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.le_show_lv2 = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_show_lv2.sizePolicy().hasHeightForWidth())
        self.le_show_lv2.setSizePolicy(sizePolicy)
        self.le_show_lv2.setText("")
        self.le_show_lv2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_show_lv2.setReadOnly(True)
        self.le_show_lv2.setObjectName("le_show_lv2")
        self.gridLayout.addWidget(self.le_show_lv2, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.le_show_lv3 = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_show_lv3.sizePolicy().hasHeightForWidth())
        self.le_show_lv3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.le_show_lv3.setFont(font)
        self.le_show_lv3.setText("")
        self.le_show_lv3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_show_lv3.setReadOnly(True)
        self.le_show_lv3.setObjectName("le_show_lv3")
        self.gridLayout.addWidget(self.le_show_lv3, 2, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 0, 1, 1)
        self.le_show_lv4 = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_show_lv4.sizePolicy().hasHeightForWidth())
        self.le_show_lv4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.le_show_lv4.setFont(font)
        self.le_show_lv4.setText("")
        self.le_show_lv4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_show_lv4.setReadOnly(True)
        self.le_show_lv4.setObjectName("le_show_lv4")
        self.gridLayout.addWidget(self.le_show_lv4, 3, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 3, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 4, 0, 1, 1)
        self.le_show_lv5 = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_show_lv5.sizePolicy().hasHeightForWidth())
        self.le_show_lv5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.le_show_lv5.setFont(font)
        self.le_show_lv5.setText("")
        self.le_show_lv5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_show_lv5.setReadOnly(True)
        self.le_show_lv5.setObjectName("le_show_lv5")
        self.gridLayout.addWidget(self.le_show_lv5, 4, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 4, 2, 1, 1)
        self.horizontalLayout_6.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_4.addWidget(self.label_22)
        self.le_show_startdessert_2 = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.le_show_startdessert_2.sizePolicy().hasHeightForWidth())
        self.le_show_startdessert_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.le_show_startdessert_2.setFont(font)
        self.le_show_startdessert_2.setText("")
        self.le_show_startdessert_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_show_startdessert_2.setReadOnly(True)
        self.le_show_startdessert_2.setObjectName("le_show_startdessert_2")
        self.horizontalLayout_4.addWidget(self.le_show_startdessert_2)
        self.label_23 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_4.addWidget(self.label_23)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_25 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_5.addWidget(self.label_25)
        self.le_show_startdessert_3 = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.le_show_startdessert_3.sizePolicy().hasHeightForWidth())
        self.le_show_startdessert_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.le_show_startdessert_3.setFont(font)
        self.le_show_startdessert_3.setText("")
        self.le_show_startdessert_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_show_startdessert_3.setReadOnly(True)
        self.le_show_startdessert_3.setObjectName("le_show_startdessert_3")
        self.horizontalLayout_5.addWidget(self.le_show_startdessert_3)
        self.label_24 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_5.addWidget(self.label_24)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        spacerItem = QtWidgets.QSpacerItem(248, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem)
        self.pb_show_part_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_show_part_2.setObjectName("pb_show_part_2")
        self.verticalLayout_4.addWidget(self.pb_show_part_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_6.addWidget(self.groupBox_2)
        self.verticalLayout_3.addWidget(self.gp_result)
        self.verticalLayout_3.setStretch(0, 3)
        self.verticalLayout_3.setStretch(1, 2)
        ficompute.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ficompute)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1112, 23))
        self.menubar.setObjectName("menubar")
        ficompute.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ficompute)
        self.statusbar.setObjectName("statusbar")
        ficompute.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(ficompute)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        ficompute.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actopen = QtWidgets.QAction(ficompute)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/image/open.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actopen.setIcon(icon)
        self.actopen.setObjectName("actopen")
        self.toolBar.addAction(self.actopen)

        self.retranslateUi(ficompute)
        QtCore.QMetaObject.connectSlotsByName(ficompute)

    def retranslateUi(self, ficompute):
        _translate = QtCore.QCoreApplication.translate
        ficompute.setWindowTitle(_translate("ficompute", "可压性计算"))
        self.gp_param.setTitle(_translate("ficompute", "可压性评价参数"))
        self.gp_weight.setTitle(_translate("ficompute", "可压性权重因子"))
        self.lb_fi.setText(_translate("ficompute", "FI"))
        self.lb_equal.setText(_translate("ficompute", "="))
        self.lb_f1.setText(_translate("ficompute", "F1"))
        self.lb_plus1.setText(_translate("ficompute", "+"))
        self.lb_f2.setText(_translate("ficompute", "F2"))
        self.lb_plus2.setText(_translate("ficompute", "+"))
        self.lb_f3.setText(_translate("ficompute", "F3"))
        self.lb_plus3.setText(_translate("ficompute", "+"))
        self.lb_f4.setText(_translate("ficompute", "F4"))
        self.lb_plus4.setText(_translate("ficompute", "+"))
        self.lb_f5.setText(_translate("ficompute", "F5"))
        self.pbmodify.setText(_translate("ficompute", "修改权重因子"))
        self.pbconfirm.setText(_translate("ficompute", "确定权重因子"))
        self.pbcompute.setText(_translate("ficompute", "计算可压性"))
        self.pbpaint.setText(_translate("ficompute", "绘图"))
        self.textEdit.setHtml(_translate("ficompute", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">F1为杨氏模量</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">F2为泊松比</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">F3为断裂韧性</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">F4为水平地应力</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">F5为垂向地应力</p></body></html>"))
        self.gp_curve.setTitle(_translate("ficompute", "可压性曲线图"))
        self.gp_result.setTitle(_translate("ficompute", "可压性筛选结果"))
        self.groupBox.setTitle(_translate("ficompute", "可压性分级标准："))
        self.label_7.setText(_translate("ficompute", "一级："))
        self.label_8.setText(_translate("ficompute", "%"))
        self.label_6.setText(_translate("ficompute", "二级："))
        self.label_9.setText(_translate("ficompute", "%"))
        self.label_10.setText(_translate("ficompute", "三级："))
        self.label_11.setText(_translate("ficompute", "%"))
        self.label_12.setText(_translate("ficompute", "四级："))
        self.label_13.setText(_translate("ficompute", "%"))
        self.label_16.setText(_translate("ficompute", "五级："))
        self.label_18.setText(_translate("ficompute", "%"))
        self.groupBox_2.setTitle(_translate("ficompute", "可压性甜点区块"))
        self.label_22.setText(_translate("ficompute", "最优甜点段起始深度："))
        self.label_23.setText(_translate("ficompute", "m"))
        self.label_25.setText(_translate("ficompute", "最优甜点段终点深度："))
        self.label_24.setText(_translate("ficompute", "m"))
        self.pb_show_part_2.setText(_translate("ficompute", "显示所有甜点层段"))
        self.toolBar.setWindowTitle(_translate("ficompute", "toolBar"))
        self.actopen.setText(_translate("ficompute", "打开文件"))
        self.actopen.setToolTip(_translate("ficompute", "打开处理完成的可压性数据文件"))
        self.actopen.setShortcut(_translate("ficompute", "Ctrl+O"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ficompute = QtWidgets.QMainWindow()
    ui = Ui_ficompute()
    ui.setupUi(ficompute)
    ficompute.show()
    sys.exit(app.exec_())
