# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rockcal.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_rockcal(object):
    def setupUi(self, rockcal):
        rockcal.setObjectName("rockcal")
        rockcal.resize(967, 709)
        self.tableView = QtWidgets.QTableView(rockcal)
        self.tableView.setGeometry(QtCore.QRect(30, 10, 441, 291))
        self.tableView.setObjectName("tableView")
        self.tableView_2 = QtWidgets.QTableView(rockcal)
        self.tableView_2.setGeometry(QtCore.QRect(490, 10, 431, 291))
        self.tableView_2.setObjectName("tableView_2")
        self.groupBox = QtWidgets.QGroupBox(rockcal)
        self.groupBox.setGeometry(QtCore.QRect(30, 340, 301, 241))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(11, 51, 248, 23))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.k_ymod = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.k_ymod.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.k_ymod.setDecimals(5)
        self.k_ymod.setMinimum(-99.0)
        self.k_ymod.setObjectName("k_ymod")
        self.horizontalLayout.addWidget(self.k_ymod)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.b_ymod = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.b_ymod.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.b_ymod.setDecimals(5)
        self.b_ymod.setMinimum(-99.0)
        self.b_ymod.setObjectName("b_ymod")
        self.horizontalLayout.addWidget(self.b_ymod)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(11, 108, 260, 22))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.k_pois = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_2)
        self.k_pois.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.k_pois.setDecimals(5)
        self.k_pois.setMinimum(-99.0)
        self.k_pois.setObjectName("k_pois")
        self.horizontalLayout_2.addWidget(self.k_pois)
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.b_pois = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_2)
        self.b_pois.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.b_pois.setDecimals(5)
        self.b_pois.setMinimum(-99.0)
        self.b_pois.setObjectName("b_pois")
        self.horizontalLayout_2.addWidget(self.b_pois)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(11, 23, 108, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(11, 80, 96, 16))
        self.label_10.setObjectName("label_10")
        self.groupBox_4 = QtWidgets.QGroupBox(rockcal)
        self.groupBox_4.setGeometry(QtCore.QRect(340, 360, 391, 211))
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 30, 221, 126))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout.addWidget(self.doubleSpinBox_2, 1, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 3, 0, 1, 1)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.gridLayout.addWidget(self.doubleSpinBox_4, 3, 1, 1, 1)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.gridLayout.addWidget(self.doubleSpinBox_3, 2, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 4, 0, 1, 1)
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_5.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.gridLayout.addWidget(self.doubleSpinBox_5, 4, 1, 1, 1)

        self.retranslateUi(rockcal)
        QtCore.QMetaObject.connectSlotsByName(rockcal)

    def retranslateUi(self, rockcal):
        _translate = QtCore.QCoreApplication.translate
        rockcal.setWindowTitle(_translate("rockcal", "岩石力学参数计算"))
        self.groupBox.setTitle(_translate("rockcal", "模量转换参数："))
        self.label.setText(_translate("rockcal", "Es"))
        self.label_2.setText(_translate("rockcal", "="))
        self.label_11.setText(_translate("rockcal", "*"))
        self.label_4.setText(_translate("rockcal", "Ed"))
        self.label_3.setText(_translate("rockcal", "+"))
        self.label_5.setText(_translate("rockcal", "μs"))
        self.label_6.setText(_translate("rockcal", "="))
        self.label_12.setText(_translate("rockcal", "*"))
        self.label_7.setText(_translate("rockcal", "μd"))
        self.label_8.setText(_translate("rockcal", "+"))
        self.label_9.setText(_translate("rockcal", "动静态杨氏模量转换"))
        self.label_10.setText(_translate("rockcal", "动静态泊松比转换"))
        self.groupBox_4.setTitle(_translate("rockcal", "地应力转换参数："))
        self.label_19.setText(_translate("rockcal", "地层压力系数"))
        self.label_14.setText(_translate("rockcal", "水平最大地应力(Sh)系数"))
        self.label_15.setText(_translate("rockcal", "上覆压力梯度"))
        self.label_13.setText(_translate("rockcal", "水平最大地应力(SH)系数"))
        self.label_16.setText(_translate("rockcal", "有效应力系数"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    rockcal = QtWidgets.QWidget()
    ui = Ui_rockcal()
    ui.setupUi(rockcal)
    rockcal.show()
    sys.exit(app.exec_())
